# Generated by Django 4.2 on 2026-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('badminton', 'Badminton'), ('swimming', 'Swimming'), ('tennis', 'Tennis'), ('football', 'Football'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('table_tennis', 'Table Tennis'), ('chess', 'Chess'), ('yoga', 'Yoga')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_experience', models.IntegerField(help_text='Years of experience')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='academy_images/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
