# Generated by Django 5.0.7 on 2026-04-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('badminton', 'Badminton'), ('swimming', 'Swimming'), ('tennis', 'Tennis'), ('football', 'Football'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('table_tennis', 'Table Tennis'), ('chess', 'Chess'), ('yoga', 'Yoga')], max_length=20)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
